#!/bin/bash

FOLDER_ID="YOUR_FOLDER_ID"
CLIENT_ID="YOUR_CLIENT_ID"
CLIENT_SECRET="YOUR_CLIENT_SECRET"
REFRESH_TOKEN="YOUR_REFRESH_TOKEN"

python ${file} --FOLDER_ID $FOLDER_ID --CLIENT_ID $CLIENT_ID --CLIENT_SECRET $CLIENT_SECRET --REFRESH_TOKEN $REFRESH_TOKEN